from nose.tools import *
from py2html.py2html import *

#'''('NAME', 'import')
'''('NAME', 'random')
('NEWLINE', '\n')
('NAME', 'from')
('NAME', 'ships')
('NAME', 'import')
('OP', '*')
('NEWLINE', '\n')
('NL', '\n')
('NAME', 'class')
('NAME', 'board')
('OP', '(')
('NAME', 'object')
('OP', ')')
('OP', ':')
('NEWLINE', '\n')
('NL', '\n')
('INDENT', '    ')
('NAME', 'def')
('NAME', '__init__')
('OP', '(')
('NAME', 'self')
('OP', ')')
('OP', ':')
('NEWLINE', '\n')
('NL', '\n')
('INDENT', '        ')
('NAME', 'self')
('OP', '.')
('NAME', 'Y_AXIS')
('OP', '=')
('NUMBER', '15')
('NEWLINE', '\n')
('NAME', 'self')
('OP', '.')
('NAME', 'X_AXIS')
('OP', '=')
('NUMBER', '25')
('NEWLINE', '\n')
('NAME', 'self')
('OP', '.')
('NAME', 'p_map')
('OP', '=')
('OP', '[')
('OP', '[')
('NUMBER', '0')
('NAME', 'for')
('NAME', 'i')
('NAME', 'in')
('NAME', 'range')
('OP', '(')
('NAME', 'self')
('OP', '.')
('NAME', 'Y_AXIS')
('OP', ')')
('OP', ']')
('NAME', 'for')
('NAME', 'i')
('NAME', 'in')
('NAME', 'range')
('OP', '(')
('NAME', 'self')
('OP', '.')
('NAME', 'X_AXIS')
('OP', ')')
('OP', ']')
('NEWLINE', '\n')
('NAME', 'self')
('OP', '.')
('NAME', 'c_map')
('OP', '=')
('OP', '[')
('OP', '[')
('NUMBER', '0')
('NAME', 'for')
('NAME', 'i')
('NAME', 'in')
('NAME', 'range')
('OP', '(')
('NAME', 'self')
('OP', '.')
('NAME', 'Y_AXIS')
('OP', ')')
('OP', ']')
('NAME', 'for')
('NAME', 'i')
('NAME', 'in')
('NAME', 'range')
('OP', '(')
('NAME', 'self')
('OP', '.')
('NAME', 'X_AXIS')
('OP', ')')
('OP', ']')
('NEWLINE', '\n')
('NL', '\n')
('NL', '\n')
('DEDENT', '')
('NAME', 'def')
('NAME', 'drawScreen')
('OP', '(')
('NAME', 'self')
('OP', ')')
('OP', ':')
('NEWLINE', '\n')
('COMMENT', '#code for drawing map')
('NL', '\n')
('COMMENT', '#print player map first on left hand side')
('NL', '\n')
('COMMENT', '#then the computer on the right side. works kinda like a typewriter, using arrays for coordinates')
('NL', '\n')
('INDENT', '        ')
('NAME', 'self')
('OP', '.')
('NAME', 'topScreen')
('OP', '(')
('OP', ')')
('NEWLINE', '\n')
('NAME', 'for')
('NAME', 'i')
('NAME', 'in')
('NAME', 'range')
('OP', '(')
('NUMBER', '0')
('OP', ',')
('NAME', 'self')
('OP', '.')
('NAME', 'Y_AXIS')
('OP', ')')
('OP', ':')
('NEWLINE', '\n')
('INDENT', '            ')
('NAME', 'if')
('NAME', 'i')
('OP', '>')
('NUMBER', '8')
('OP', ':')
('NEWLINE', '\n')
('INDENT', '                ')
('NAME', 'yaxis')
('OP', '=')
('NUMBER', '3')
('NEWLINE', '\n')
('DEDENT', '')
('NAME', 'else')
('OP', ':')
('NEWLINE', '\n')
('INDENT', '                ')
('NAME', 'yaxis')
('OP', '=')
('NUMBER', '4')
('NEWLINE', '\n')
('COMMENT', '#draw human y axis')
('NL', '\n')
('DEDENT', '')
('NAME', 'mapy')
('OP', '=')
('STRING', "'%s%d'")
('OP', '%')
('OP', '(')
('STRING', "' '")
('OP', '*')
('NAME', 'yaxis')
('OP', ',')
('NAME', 'i')
('OP', '+')
('NUMBER', '1')
('OP', ')')
('NEWLINE', '\n')
('COMMENT', '#loop for y axis')
('NL', '\n')
('COMMENT', '#human = true')
('NL', '\n')
('COMMENT', '#CLEAN THIS CODE TO MAKE IT READABLE TO AVOID EASY PROBLEMS')
('NL', '\n')
('NAME', 'player')
('OP', '=')
('NAME', 'True')
('NEWLINE', '\n')
('NAME', 'for')
('NAME', 'j')
('NAME', 'in')
('NAME', 'range')
('OP', '(')
('NUMBER', '0')
('OP', ',')
('NAME', 'self')
('OP', '.')
('NAME', 'X_AXIS')
('OP', ')')
('OP', ':')
('NEWLINE', '\n')
('COMMENT', '#loop for x axis')
('NL', '\n')
('INDENT', '                ')
('NAME', 'mapy')
('OP', '+=')
('NAME', 'self')
('OP', '.')
('NAME', 'drawOcean')
('OP', '(')
('NAME', 'player')
('OP', ',')
('NAME', 'j')
('OP', ',')
('NAME', 'i')
('OP', ')')
('NEWLINE', '\n')
('NL', '\n')
('DEDENT', '')
('NAME', 'player')
('OP', '=')
('NAME', 'not')
('NAME', 'player')
('NEWLINE', '\n')
('COMMENT', '#make space')
('NL', '\n')
('NAME', 'if')
('NAME', 'i')
('OP', '>')
('NUMBER', '8')
('OP', ':')
('NEWLINE', '\n')
('INDENT', '                ')
('NAME', 'mapy')
('OP', '+=')
('STRING', "' '")
('OP', '*')
('NUMBER', '18')
('NEWLINE', '\n')
('DEDENT', '')
('NAME', 'else')
('OP', ':')
('NEWLINE', '\n')
('INDENT', '                ')
('NAME', 'mapy')
('OP', '+=')
('STRING', "' '")
('OP', '*')
('NUMBER', '19')
('NEWLINE', '\n')
('COMMENT', '#draw computer y axis')
('NL', '\n')
('DEDENT', '')
('NAME', 'mapy')
('OP', '+=')
('STRING', "'%d'")
('OP', '%')
('OP', '(')
('NAME', 'i')
('OP', '+')
('NUMBER', '1')
('OP', ')')
('NEWLINE', '\n')
('NL', '\n')
('NAME', 'for')
('NAME', 'j')
('NAME', 'in')
('NAME', 'range')
('OP', '(')
('NUMBER', '0')
('OP', ',')
('NAME', 'self')
('OP', '.')
('NAME', 'X_AXIS')
('OP', ')')
('OP', ':')
('NEWLINE', '\n')
('INDENT', '                ')
('NAME', 'mapy')
('OP', '+=')
('NAME', 'self')
('OP', '.')
('NAME', 'drawOcean')
('OP', '(')
('NAME', 'player')
('OP', ',')
('NAME', 'j')
('OP', ',')
('NAME', 'i')
('OP', ')')
('NEWLINE', '\n')
('DEDENT', '')
('NAME', 'print')
('NAME', 'mapy')
('NEWLINE', '\n')
('NL', '\n')
('DEDENT', '')
('NAME', 'print')
('STRING', "'%sLegend: U - your ship, O - miss, H - hit, S - sunk'")
('OP', '%')
('OP', '(')
('STRING', "' '")
('OP', '*')
('NUMBER', '12')
('OP', ')')
('DEDENT', '')
('DEDENT', '')
('ENDMARKER', '')'''#
   

